### ISSUE TITLE
gameboard style adjustments

### ISSUE THREAD

**Issue by perennialAutodidact** [perennialAutodidact/memory-snap#52]
The width of the `TileGrid` component should be narrower. Bootstrap's `container`, `row` and `col` classes can be used to limit its width. It should be 12 columns wide on mobile and 6 or 8 columns wide (whichever looks better) on desktop

**Comment by russfraze** [comment]
![Screen Shot 2023-09-29 at 6 39 15 PM](https://github.com/perennialAutodidact/memory-snap/assets/81979567/055484f2-8680-4bad-b6b3-0314ae248aad)
I think 6 looks good on desktop. Theres ten here so you could picture three times that fitting in this. 

When it comes to mobil, here is iphone size:
![Screen Shot 2023-09-29 at 6 37 07 PM](https://github.com/perennialAutodidact/memory-snap/assets/81979567/6173c004-7586-4116-a5a0-5f50d98c3236)

This issue says 12 in mobile but I feel like thats too small and you wouldn't be able to see what the images are. I feel like it looks good with 4 across but let me know what you think.

**Comment by perennialAutodidact** [comment]
@russfraze, These are the styles I came up with: 

`components/Game/GameBoard/Tile/style.scss`
```scss
@import '~styles/memory-snap-mixins';

.tile {
  // position: relative;
  // height: 100px;
  // overflow: hidden;
  // padding-bottom: 100%;
  height: 100px;
  width: 100px;

  @include breakpoint(md) {
    height: 200px;
    width: 200px;
  }

  img {
    width: 100%;
    height: 100%;
    // position: absolute;
  }
}

```

`styles/_memory-snap-mixins.scss`
```scss
@import '~bootstrap/scss/functions';
@import '~bootstrap/scss/variables';
@import '~bootstrap/scss/mixins';

@mixin breakpoint($size) {
  @include media-breakpoint-up(md) {
    @content;
  }
}
```

`components/Game/GameBoard/TileGrid/index.jsx`
```javascript
//...
return (
  <div id="tile-grid" className="container mt-5">
    <div className="row">
      <div className="col-12 col-md-6 offset-md-3">
        <div className="d-flex justify-content-center flex-wrap gap-3">
          {!tiles
            ? null
            : tiles.map((tile, index) => (
                <div className="tile" key={index}>
                  <Tile
                    isMatched={tile.isMatched}
                    faceUp={tile.faceUp}
                    onFlip={onFlipTile}
                    key={index}
                    index={index}
                    id={tile.id}
                    photo={tile.photo}
                  />
                </div>
              ))}
        </div>
      </div>
    </div>
  </div>
)
// ...
```

Which looks like this

|Mobile|Desktop|
|-|-|
|![Image](https://github.com/perennialAutodidact/memory-snap/assets/56051123/3769fc11-2355-4a14-bd6d-5e3b0af40546)|![Image](https://github.com/perennialAutodidact/memory-snap/assets/56051123/7825818c-bf35-4769-a726-19bead6ce597)|
